FROM python:3.10.1

WORKDIR /workspace

COPY frontend/requirements.txt /tmp/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /tmp/requirements.txt

EXPOSE 8501

CMD ["streamlit", "run", "frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0","--server.fileWatcherType=poll","--server.runOnSave=True"]
