version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: todo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: .devcontainer/backend/Dockerfile.fastapi
    environment:
      DATABASE_URL: mysql+pymysql://user:password@db/todo_db
      SECRET_KEY: your_secret_key
    volumes:
      - .:/workspace:consistent
    networks:
      - app-network
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: .devcontainer/frontend/Dockerfile.streamlit
    volumes:
      - .:/workspace:consistent
    networks:
      - app-network
    ports:
      - "8501:8501"
    depends_on:
      - backend

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
